version: '3.3'

volumes:
  gems-data:
    driver: local

services:
  app:
    container_name: bravado.quest.app
    build: .
    image: bravado-quest
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DISABLE_SPRING: 1
    command: npm run server
    volumes:
      - '.:/usr/src/app'
      - gems-data:/usr/local/bundle
    ports:
      - '3000:3000'
    stdin_open: true
    env_file: .env
    tty: true

networks:
  default:
    driver: bridge
